config/routes.rb
Rails.application.routes.draw do

  root 'events#new'

  resources :events do
    resources :locations
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_one :location
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@events = Event.all
	end
	def new
		@event = Event.new
	end
	def create
		@event = Event.new(event_params)
		respond_to do |format|
			if @event.save
				format.html { redirect_to @event, notice: 'Event was successfully created.'}
				format.json { render json:show}
			else
				format.html { render action:'new'}
				format.json { render json: @event.errors, :status => :unprocessable_entity}
			end
		end
	end
	def show
		@event = Event.find(params[:id])
	end
	def edit
		@event = Event.find(params[:id])
	end
    def update
    	@event = Event.find(params[:id])
    	respond_to do |format|
    		if @event.update(event_params)
    			format.html { redirect_to @event, notice: 'Event was successfully Updated.'}
    			format.json { render json: show}
    		else
    			format.html { render action: 'update'}
    			format.json { render json: @event.errors, :status => :unprocessable_entity}
    		end
    	end
    end
    def destroy
    	@event = Event.find(params[:id])
    	@event.destroy
    	redirect_to events_path
    end
	private
	def event_params
		params.require(:event).permit(:name, :age, :email, :comment)
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
<% if @event.errors.any? %>
<div id= 'error explanation'>
	<h2><%= pluralize(@event.errors.count,'error')%>Prohibited event from being saved: %></h2>
	<ul>
		<% @event.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<p>
<%= f.label :Name %>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :Age %>
<%= f.text_field :age %>
</p>
<p>
	<%= f.label :Email %>
	<%= f.text_field :email %>
</p>
<p> 
    <%= f.label :Comment %>
    <%= f.text_area :comment %>
</p>
<p> 
    <%= f.submit :create %>
</p>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<%= render 'form' %>

app/views/events/index.html.erb
<h1>Listing Events</h1>
<table border="1">
	<tr>
		<th>Name</th>
		<th>Age</th>
		<th>Email</th>
		<th>Comment</th>
	</tr>
 <% @events.each do |event| %>
    <tr>
    <td><%= event.name %></td>
    <td><%= event.age %></td>
    <td><%= event.email %></td>
    <td><%= event.comment %></td>
    <td><%= link_to 'show', event_path(event) %></td>
    <td><%= link_to 'edit', edit_event_path(event) %></td>
    <td><%= link_to 'delete', event_path(event),
            :method => :delete, data: { clear: 'Are you sure?' }%></td>
    </tr>
<% end %> 
</table>

<%= link_to 'newevent', new_event_path %>
<%= link_to 'location', new_event_location_path(event) %>

app/views/events/new.html.erb
<h1>New Event</h1>
<p><strong>I AM GOPIKRISHNA</strong></p>
<%= render 'form' %>

app/views/events/show.html.erb
<% if flash[:notice] %>
<div id="notice"><%= flash[:notice] %></div>
<% end %>
<p>
	<b>Name</b>
	<%= @event.name %>
</p>
<p>
	<b>Age</b>
	<%= @event.age %>
</p>
<p>
	<b>Email</b>
	<%= @event.email %>
</p>
<p>
	<b>Comment</b>
	<%= @event.comment %>
</p>

<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>